name: Docker

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    name: Build
    uses: dargmuesli/github-actions/.github/workflows/docker3.yml@0.29.0
    secrets:
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USER_NAME: ${{ secrets.DOCKER_HUB_USER_NAME }}
  release-semantic:
    needs: build
    name: Semantic Release
    uses: dargmuesli/github-actions/.github/workflows/release-semantic.yml@0.28.8
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
